export const SECOND_YEAR_PORS = [
  "Excomm",
  "Project Lead",
  "Doc Head",
  "Treasurer",
  "HR Head",
  "Dev Team Lead",
  "Design Team Lead",
  "Inventory Head",
  "Classhead 6",
  "Classhead 12",
  "Classhead 8",
  "Classhead 10",
  "Classhead 9",
  "Classhead 7",
  "Classhead 1-3",
  "Classhead 11",
  "Classhead 4-5",
  "Unnati Head",
  "Initiatives Head",
  "HR Head + Doc Head",
  "HR Head + Treasurer",
];
